/* ============================================================
   1. SHIPPED PROGRAMMES

   The public build ships one worked example and one blank
   programme. Meridian Grid is invented. Every company, person
   and number below is fictional, and any resemblance to a real
   business is accidental.

   Real client work lives in exported JSON files that never
   enter this repository. Load one with the Import button.
   ============================================================ */

const DEMO = {
  id:'demo', name:'Meridian Grid', short:'MG', url:'https://example.com',
  archetype:'infra',
  industry:'EV charging infrastructure for commercial car parks',
  hq:'Manchester, operating across 14 UK cities',
  contact:'Head of Marketing',

  exec:{
    thesis:'You sell something nobody has budgeted for, to a list of companies that fits on one page, where the person who owns the car park, the person who runs the building and the person who signs the cheque are three different people who rarely talk to each other.',
    why:[
      'The buyers can be listed. There are roughly 300 organisations in the UK that own enough commercial parking to matter, and we can name them.',
      'One car park is worth eight to twelve years of revenue, so it pays to do real work per account.',
      'Four to seven people touch the decision, across property, facilities, sustainability and finance.',
      'The reasons to buy are announced in public. Planning applications, refurbishments, fleet commitments and net zero targets all get published.',
      'Buyers choose on whether you will still be operating the chargers in year seven, which is a story about credibility rather than price.'
    ],
    what:'A ninety day pilot across 20 named organisations in two priority sectors, run by marketing and sales together. Account research, mapping who sits on each decision, content written for specific roles, LinkedIn, letters from leadership, email, one roundtable, and sales following up to agreed timings.',
    notThis:'It is worth being clear about what this is not. Impressions and form fills can both climb for three months while nothing commercially useful happens, so we are not asking to be judged on either.',
    how:[
      'Ten stages, worked through in order, each signed off before we build on it.',
      'You approve the account list, provide the engineers, check every claim we publish, and do the selling. We do the research, the scoring, the content, the media and the reporting.',
      'No account gets personalised work until somebody in sales has agreed to chase it.',
      'We watch for triggers continuously and get the first relevant contact out inside two working days.',
      'Weekly tuning, a monthly read for your board, and an honest decision at week twelve about whether to scale it, change it or stop.'
    ],
    context:'Every commercial landlord now has a net zero commitment and a car park full of combustion engines. The pressure is real but nobody has a line in the budget for it, so the conversation stalls in the gap between the sustainability team who want it and the finance team who have not costed it. Marketing today speaks to all sectors in one voice and generates enquiries that sales cannot qualify. The gap is not awareness. It is that nothing turns a published net zero pledge into a funded project inside a company we have named.'
  },

  successMetrics:[
    ['Accounts that engage','12 of the 20 named accounts','At least one real interaction from somebody on the decision map','ZAMSTARS'],
    ['People reached per account','Three or more roles in every priority account','Different mapped roles engaged at Tier 1 and Tier 2','ZAMSTARS'],
    ['Real conversations','8 to 12 over the pilot','A first proper commercial conversation with a mapped buyer','Client Sales'],
    ['Site surveys delivered','5 to 8 accounts','Accepted and completed, not just offered','Client Pre-Sales'],
    ['Opportunities in the CRM','3 to 5','Created and accepted by sales','Client Sales'],
    ['Account-level reporting running','Live by end of week 4','Engagement visible per account rather than only in total','ZAMSTARS'],
    ['What we learned','Written up by week 12','Which sector, trigger and message actually produced conversations','ZAMSTARS + Client']
  ],
  metricsNote:'These are planning targets rather than promises. To set them properly we need the current meeting to opportunity and opportunity to win rates, which nobody has been able to produce yet. Finding those is a week one job, and until then these are our best estimate.',

  profile:{
    whatTheyDo:'Meridian Grid funds, installs and operates EV charging in commercial car parks. The landlord provides the space and the grid connection. Meridian pays for the hardware, runs the network, handles maintenance and billing, and shares the revenue.',
    revenueModel:'The landlord pays nothing upfront. Meridian funds the installation and earns from charging sessions, a share to the landlord, and service contracts on the hardware. Revenue continues for the life of the agreement, so how much of a portfolio you cover matters far more than the first site.',
    proof:[
      '340 sites live across 14 cities',
      '2,100 charge points under management',
      '99.4% network uptime across the estate over 12 months',
      'Average 11 months from agreement to first revenue for the landlord',
      'No capital cost to the property owner under the standard model',
      'Backed by two infrastructure funds with a 15 year horizon'
    ],
    diff:[
      'No capital cost to the property owner',
      'We operate the network ourselves rather than handing it to a third party',
      'One agreement covers install, maintenance, billing and support',
      'Designed to work in existing car parks, not just new build',
      'Funded for 15 years, so we will be here to fix it in year seven'
    ],
    gtm:'Mostly inbound and referrals from energy consultants, with some outbound to property managers. Good content exists but it goes to an audience rather than a list, and every sector hears the same message.',
    cycle:'5 to 11 months for a portfolio agreement, 3 to 5 months for a single site',
    acv:'£45k to £400k per site in lifetime revenue share, with portfolio deals materially higher',
    competitors:'The large charge point operators, the energy majors moving into charging, and regional installers. The one that wins most often is doing nothing, or putting in four chargers to satisfy a planning condition and calling it solved.',
    challenge:'Nobody wakes up wanting charge points. They wake up with a net zero commitment they have not costed, tenants asking questions at renewal, and a planning condition on the next development. So the job is not generating enquiries. It is turning a published pledge into a funded project, inside companies we have named.'
  },

  objective:{
    goal:'Build real pipeline from 20 named organisations in two priority sectors, and turn the single sites we already run into portfolio agreements.',
    horizon:'90 day pilot, then scale, change or stop',
    pipelineTarget:'3 to 5 opportunities in 90 days, and £4m weighted pipeline over four quarters',
    accountTarget:20,
    budget:1800000
  },

  icpFit:[
    'More than 500 parking spaces across the portfolio',
    'More than one site, or a portfolio still growing',
    'A published net zero or ESG commitment with a date attached',
    'Tenants or visitors who expect charging to be there',
    'Something being built or refurbished right now',
    'Cities where we already have engineers',
    'Grid capacity that will not need a two year upgrade',
    'A central property, facilities or sustainability team to talk to'
  ],
  disqualify:[
    'Fewer than 100 spaces, where the numbers do not work.',
    'Somewhere we cannot get an engineer to within four hours.',
    'Grid capacity so constrained that the connection cost swallows the return.',
    'Locked into an exclusive agreement with years left to run.',
    'Nothing happening, nobody we know, and no visible champion.',
    'Sales has neither the time nor the intention to chase it this quarter.'
  ],

  segments:[
    { id:'d-office', name:'Offices and business parks', on:true, colour:C.pink, priority:'A',
      desc:'Landlords and asset managers running multi-tenant offices and out of town business parks.',
      whyNow:'Occupiers now ask about charging on the site visit, and it is starting to appear in renewal negotiations.',
      why:'One agreement can cover a dozen sites. The highest lifetime value on the list, and the only sector where a single relationship compounds.',
      problems:['Net zero commitments with no costed plan behind them','Tenants asking for charging at renewal','Four chargers installed to satisfy planning, now permanently oversubscribed','No capital budget for anything that is not revenue generating','Nobody sure whether the grid connection can take it'],
      fit:['500+ spaces across the portfolio','Three or more sites','Published ESG commitment','Occupiers in professional services or technology'],
      size:'About 90 qualifying groups, 11 in the pilot' },
    { id:'d-retail', name:'Retail and shopping centres', on:true, colour:C.teal, priority:'A',
      desc:'Shopping centre owners and large format retail parks.',
      whyNow:'Charging keeps visitors on site for longer, which retail landlords can measure in a way office landlords cannot.',
      why:'The dwell time argument makes the business case itself, so the sale is shorter and the champion is easier to find.',
      problems:['Visitors leaving to charge elsewhere','Anchor tenants asking what the plan is','Large car parks earning nothing per square metre','Competing centres already advertising charging'],
      fit:['400+ spaces on one site','Footfall reported to investors','Central asset management team'],
      size:'About 60 groups, 3 in the pilot' },
    { id:'d-hotel', name:'Hotels and hospitality', on:true, colour:C.gold, priority:'B',
      desc:'Hotel groups where guests arrive by car and increasingly expect to leave with a full battery.',
      whyNow:'Charging is now a filter on the booking platforms, so its absence removes the property from the results rather than just disappointing the guest.',
      why:'The clearest link between the investment and a number the general manager already reports.',
      problems:['Guests filtering the property out before they ever see it','Reviews mentioning the lack of charging','Inconsistent provision across the group','Charge points installed and then left broken'],
      fit:['15+ properties or a national brand','Guests arriving by car','Central procurement or brand standards'],
      size:'About 40 groups, 3 in the pilot' },
    { id:'d-logistics', name:'Logistics and fleet depots', on:true, colour:C.violet, priority:'Expansion',
      desc:'Distribution centres and depots facing a fleet transition with a deadline.',
      whyNow:'Fleet electrification targets have dates attached, and depot charging is the part nobody has costed.',
      why:'The most urgent buyers on the list, though the technical requirement is heavier and the grid work is larger.',
      problems:['Fleet targets with no depot plan','Overnight charging demand that dwarfs the current connection','Vehicles ordered before the infrastructure was scoped'],
      fit:['50+ vehicles based at one depot','Published fleet transition target','Freehold or long lease'],
      size:'About 120 operators, 3 in the pilot' },
    { id:'d-health', name:'Hospitals and healthcare', on:false, colour:C.ink3, priority:'Parked',
      desc:'Hospital trusts and private healthcare groups with large staff and visitor car parks.',
      whyNow:'Public sector net zero requirements are now contractual rather than aspirational.',
      why:'Parked for phase two. Real demand, but procurement runs through frameworks that need a different approach.',
      problems:['Staff parking pressure','Public sector carbon reporting','Capital constraints'],
      fit:['800+ spaces','Framework access'], size:'About 200 sites' },
    { id:'d-resi', name:'Residential and build to rent', on:false, colour:C.ink3, priority:'Parked',
      desc:'Build to rent operators and large managed residential schemes.',
      whyNow:'Charging now appears in letting brochures as standard.',
      why:'Parked. Smallest revenue per site, and the buyer is often the same developer we are already talking to commercially.',
      problems:['Resident demand outstripping provision','Allocation disputes between residents'],
      fit:['200+ units','Managed operations'], size:'About 150 operators' }
  ],

  personas:[
    { id:'d-asset', role:'Head of Asset Management', crole:'econ', colour:ROLE_COL.econ, segs:['d-office','d-retail'],
      goal:'Protect rental income and keep the portfolio competitive at renewal.',
      pain:'Occupiers raise charging at renewal. Every site was solved differently by whoever happened to be managing it that year, so there is no standard and no data.',
      pitch:'Charging becomes part of what the building is worth instead of a cost you have not budgeted for. One standard across the portfolio, and we pay for it.',
      objection:'"There is no capital budget for this, and I am not giving up parking revenue for something I cannot measure."',
      proof:'No capital cost, 340 sites already live, and a revenue share that makes the car park earn rather than spend.',
      content:'A business case with their own portfolio numbers in it',
      channels:['LinkedIn','Industry events','Broker referral','Direct mail'] },
    { id:'d-fm', role:'Head of Facilities', crole:'ops', colour:ROLE_COL.ops, segs:['d-office','d-retail','d-hotel'],
      goal:'Fewer complaints and nothing new to maintain.',
      pain:'Owns every complaint about the four broken chargers and controls none of the equipment. Chases a supplier who does not answer.',
      pitch:'We operate the network ourselves, so the complaint stops with us. One number to ring and contracted uptime.',
      objection:'"My team cannot take on another system, and the last lot left us with four dead units."',
      proof:'99.4% uptime across the estate, maintenance included in the agreement, and we operate rather than subcontract.',
      content:'The SLA, how monitoring works, and a site like theirs that we already run',
      channels:['Email','On-site review','Facilities forums'] },
    { id:'d-sust', role:'Head of Sustainability', crole:'champ', colour:ROLE_COL.champ, segs:['d-office','d-retail','d-hotel','d-logistics'],
      goal:'Turn a published commitment into something that has actually happened.',
      pain:'Owns the target, controls no budget, and has to persuade finance every time. Needs numbers that survive an auditor.',
      pitch:'A funded route to a commitment you have already published, with reporting your auditor will accept.',
      objection:'"I can get everyone to agree it is a good idea. I cannot get anyone to pay for it."',
      proof:'No capital cost removes the objection finance usually raises, and reporting comes as standard.',
      content:'A deck they can present as their own, plus an email they can forward',
      channels:['LinkedIn','Sustainability networks','Roundtable','Email'] },
    { id:'d-proj', role:'Development or Projects Director', crole:'proj', colour:ROLE_COL.proj, segs:['d-office','d-retail','d-logistics'],
      goal:'Deliver on programme with no surprises from the grid connection.',
      pain:'Charging arrives as a planning condition late in the programme, when the ducting is already in the ground.',
      pitch:'Designed in during groundworks costs a fraction of what retrofitting costs, and we will do the grid assessment before you commit.',
      objection:'"Bringing this in now will delay the programme and I have no float left."',
      proof:'A grid assessment before design freeze, and installations phased around live operations.',
      content:'A rollout plan and a checklist they can hand to their contractor',
      channels:['Technical sessions','Site visits','Design consultations'] },
    { id:'d-fin', role:'Finance Director', crole:'proc', colour:ROLE_COL.proc, segs:['d-office','d-retail','d-hotel','d-logistics'],
      goal:'No unbudgeted capital, defensible commercials, and nothing contingent hiding in the contract.',
      pain:'A 15 year agreement with access rights attached looks like risk on a page somebody else drafted.',
      pitch:'No capital, predictable operating costs, and an asset that earns rather than spends.',
      objection:'"What exactly are we committing to, for how long, and what happens if you are bought?"',
      proof:'Standard commercial framework, two infrastructure funds behind us, and 340 executed agreements.',
      content:'Total cost of ownership, our credentials, and answers to the awkward questions',
      channels:['Business case','Formal proposal','Reference call'] },
    { id:'d-tech', role:'Head of Engineering or M&amp;E', crole:'tech', colour:ROLE_COL.tech, segs:['d-office','d-logistics'],
      goal:'Know the connection will hold and the installation will not disrupt the site.',
      pain:'No idea what the incoming supply can actually take, and the last assessment was a spreadsheet from 2019.',
      pitch:'A proper grid capacity assessment before anyone signs anything, and load management so you do not pay for an upgrade you do not need.',
      objection:'"Our supply cannot take it, and an upgrade would cost more than the project."',
      proof:'Load management as standard, phased installation, and an assessment done before commitment.',
      content:'An architecture note and a working session with our engineers',
      channels:['Technical sessions','Site survey','Peer reference'] }
  ],

  /* [name, segment, city, incumbent, potential, fit, trigger, geography, reference, warm door, interest, note] */
  accounts:[
    ['Harbourline REIT','d-office','Manchester','Four units, unmaintained',10,10,8,10,9,6,8,'Largest portfolio on the list and a published 2030 target. Two sites already under discussion.'],
    ['Kingsway Retail Group','d-retail','Leeds','None',9,9,7,10,9,3,5,'Nine centres, all with oversized car parks earning nothing.'],
    ['Ashcroft Hotels','d-hotel','Birmingham','Meridian (2 sites)',8,9,7,9,8,9,8,'Already a client at two properties. Expansion rather than acquisition, and the best return on the list.'],
    ['Castlebrook Estates','d-office','Bristol','Regional installer',9,9,7,9,8,4,6,'Refurbishment programme announced across four business parks.'],
    ['Vantage Office Group','d-office','London','Mixed',9,9,6,9,7,4,4,'Central asset management team, so decisions cover the whole portfolio.'],
    ['Silverbrook Centres','d-retail','Glasgow','Energy major',8,8,7,9,7,3,5,'Competing centre nearby has just advertised charging.'],
    ['Pemberton Property','d-office','Manchester','None',7,9,7,9,6,4,5,'Two new developments in groundworks, so we can be designed in.'],
    ['Belmont Collection','d-hotel','Edinburgh','Fragmented',8,8,6,9,8,3,4,'Brand standards are set centrally, so one decision cascades to every property.'],
    ['Trentham Logistics','d-logistics','Birmingham','None',8,8,7,8,6,3,5,'Fleet transition target for 2029 with no depot plan behind it.'],
    ['Ardent Systems','d-office','Reading','Landlord provided',7,8,6,9,7,3,5,'Single large campus and a workforce that already drives electric.'],
    ['Grayling Developments','d-office','Leeds','None',7,8,6,9,6,4,4,'Planning conditions on two schemes now in design.'],
    ['Halden Malls','d-retail','Nottingham','Regional installer',7,8,6,9,6,3,4,'Dwell time is already a board level metric here.'],
    ['Beckworth Financial','d-office','London','Landlord provided',7,8,5,9,8,2,4,'Would be a strong reference in financial services.'],
    ['Rivergate Resorts','d-hotel','Cardiff','None',6,7,7,8,6,3,4,'Booking platform filters are costing them visibility right now.'],
    ['Oakfield Distribution','d-logistics','Sheffield','None',7,7,6,8,5,3,4,'Vehicles on order before the depot was scoped.'],
    ['Corvin Technologies','d-office','Cambridge','Landlord provided',6,7,5,9,7,2,3,'Growing headcount and a stated staff benefit interest.'],
    ['Northmoor Estates','d-office','Newcastle','Fragmented',6,7,5,8,5,3,3,'Smaller portfolio but an engaged sustainability lead.'],
    ['Delmar Sciences','d-office','Oxford','Landlord provided',5,6,4,8,6,2,2,'Good fit on paper but nothing happening this year.'],
    ['Marlow Freight','d-logistics','Hull','None',5,6,4,7,4,2,2,'Depot is outside our current engineering coverage.'],
    ['Everline Media','d-office','London','Landlord provided',4,5,3,8,5,1,2,'Leased space only, so they do not control the car park.']
  ],

  coreMessage:'Meridian Grid turns car parks into charging infrastructure at no capital cost, and then runs it for fifteen years.',

  umbrellas:[
    { id:'d-u1', name:'For asset managers and landlords', segs:['d-office','d-retail'],
      line:'Your car park is the largest thing you own that earns nothing.',
      target:'Heads of Asset Management, Portfolio Directors, property CXOs',
      focus:'Rental income, renewals, portfolio standard, no capital cost',
      proof:'340 sites live · no capital cost · revenue share from day one',
      supporting:['Charging becomes something the asset earns from rather than pays for','One standard across the portfolio instead of a different answer at every site','Occupiers stop raising it at renewal','Reporting your investors will accept','No capital cost under the standard model'],
      body:'Occupiers are already asking about charging before they ask about rent. Right now every site in the portfolio has a different answer, and none of them earn anything.' },
    { id:'d-u2', name:'For sustainability leads', segs:['d-office','d-retail','d-hotel','d-logistics'],
      line:'You have already published the commitment. This is how it gets funded.',
      target:'Heads of Sustainability, ESG leads, net zero programme managers',
      focus:'Turning a published target into delivered projects, with reporting that survives audit',
      proof:'No capital cost · reporting as standard · 2,100 charge points under management',
      supporting:['Removes the funding objection finance normally raises','Reporting your auditor will accept, produced automatically','Delivery you can point at within the current financial year','A standard you can apply across every site','Nothing new for the facilities team to run'],
      body:'The commitment is already public. The problem has never been agreement, it has been that nobody costed it.' },
    { id:'d-u3', name:'For hotel groups', segs:['d-hotel'],
      line:'Guests are filtering your property out before they ever see it.',
      target:'Group Operations Directors, brand standards leads, general managers',
      focus:'Bookings, reviews, consistency across the group',
      proof:'Uptime you can quote to a guest · consistent provision across every property',
      supporting:['Charging is a filter on the booking platforms now','Reviews mention it whether you invest or not','One standard across every property in the group','Nothing for the property team to maintain','Revenue share rather than a cost line'],
      body:'A guest will forgive a slow lift. They will not book at all if the filter removes you from the list.' }
  ],

  hooks:[
    'Your car park is the largest thing you own that earns nothing.',
    'Four chargers, permanently occupied, is not a plan.',
    'You published the target. Nobody costed it.',
    'Guests are filtering you out before they see the photographs.',
    'Retrofitting after the ducting goes in costs four times as much.'
  ],

  journey:[
    { name:'Not their problem yet', vg:'ret',
      mindset:'Someone else owns this. The energy company, the developer, whoever fitted it out last.',
      question:'Whose problem is this, actually?',
      thinks:'We put four in to satisfy planning. That box is ticked.',
      does:'Nothing. Forwards the occasional complaint to facilities.',
      channels:['Organic social','Industry press','SEO'],
      assets:['Point of view on parking as an asset','Category explainer','Planning condition guide'],
      kpi:'Reach and article engagement inside named accounts',
      owner:'ZAMSTARS Content',
      friction:'Nobody thinks they own it, so there is nothing to sell against yet. The job here is giving the problem a name.' },
    { name:'Now it is theirs', vg:'acq',
      mindset:'An occupier raised it at renewal, or the ESG report is due and the numbers look thin.',
      question:'What is this costing us?',
      thinks:'Two tenants mentioned charging in renewal talks. That is rent at risk.',
      does:'Asks facilities for the history. Looks at what other landlords have done.',
      channels:['High intent search','LinkedIn','Cost calculator'],
      assets:['Cost of doing nothing calculator','Occupier expectation benchmark','Renewal risk one-pager'],
      kpi:'Calculator completions and search clicks from named accounts',
      owner:'ZAMSTARS Paid and Web',
      friction:'They can feel the cost but cannot size it. Give them the number in their own units: spaces, sites, square feet.' },
    { name:'Working out the options', vg:'acq',
      mindset:'There is a category here. Own it, lease it, or let somebody else fund it.',
      question:'What are my options and what do they each cost me?',
      thinks:'I do not want to become an expert in this. I want to know which of the three models to pick.',
      does:'Reads a comparison. Asks a peer landlord what they did.',
      channels:['Gated content','Document ads','Technical session'],
      assets:['Funding models compared','Grid capacity primer','Sector guide'],
      kpi:'Guide downloads from target accounts',
      owner:'ZAMSTARS Content',
      friction:'Technical vocabulary becomes the barrier. Translate every term into an operational outcome in the same sentence.' },
    { name:'Building a shortlist', vg:'acq',
      mindset:'Who can do this across the whole portfolio and still be here in year seven?',
      question:'Who can do this at my scale without falling over?',
      thinks:'I need someone who has done three hundred sites, not three. And I need to know who is paying.',
      does:'Asks peers. Checks references. Looks for logos from their own sector.',
      channels:['Account page','Case studies','Peer reference','Letter from leadership'],
      assets:['Sector case study pack','Named account page','Funding credentials'],
      kpi:'Page visits from mapped roles, reference calls requested',
      owner:'ZAMSTARS Web and Client Sales',
      friction:'This is the elimination round. Missing sector proof loses it here, not price.' },
    { name:'Proving it works', vg:'exp',
      mindset:'Prove it on my site, not in a deck.',
      question:'Will the connection take it, and what will it disrupt?',
      thinks:'Show me the grid assessment for this car park. Then tell me exactly what you dig up.',
      does:'Grants site access. Brings in engineering and projects.',
      channels:['Site survey','Design review','Technical session','Reference visit'],
      assets:['Grid capacity assessment','Phased installation plan','Reference site visit'],
      kpi:'Surveys accepted and completed, roles present at the read-out',
      owner:'Client Pre-Sales',
      friction:'Engineering can stop this on grid capacity alone. Bring them in before the survey rather than after.' },
    { name:'Getting it approved', vg:'exp',
      mindset:'The technology is fine. Now, what are we signing and for how long.',
      question:'Can we get this past finance and legal without a three month loop?',
      thinks:'No capital cost sounds good. A fifteen year access right sounds like something legal will slow down.',
      does:'Routes to finance and legal. Asks for precedent agreements.',
      channels:['Business case','Formal proposal','Precedent pack','Reference call'],
      assets:['Total cost model','Standard agreement','Funding credentials'],
      kpi:'Proposals issued, median days in legal review',
      owner:'Client Commercial',
      friction:'The longest stall in the journey. Get ahead of it with a precedent pack and a finance director who will take a call.' },
    { name:'First site goes live', vg:'exp',
      mindset:'One site is running. Everyone is watching whether the promise held.',
      question:'Did they do what they said?',
      thinks:'If this install is clean I will stop defending the decision internally.',
      does:'Watches utilisation and complaints. Reports upward at the first review.',
      channels:['On-site delivery','Reporting','Go-live comms'],
      assets:['Launch comms kit','Utilisation dashboard','Occupier announcement templates'],
      kpi:'Uptime against SLA, utilisation in the first 90 days',
      owner:'Client Delivery',
      friction:'Marketing usually vanishes at this point, which is a mistake. The next eight sites get won right here.' },
    { name:'Rolling it out', vg:'ret',
      mindset:'It worked. Where next, and can we make it the standard?',
      question:'Which sites are next, and can we write this into the specification?',
      thinks:'I would rather have one standard than negotiate this eight more times.',
      does:'Builds the internal case. Introduces us to other asset managers.',
      channels:['Quarterly review','Internal roadshow','Portfolio roadmap'],
      assets:['Portfolio rollout plan','Internal business case','Cross-site performance report'],
      kpi:'Sites added per existing relationship',
      owner:'Client Account Management',
      friction:'Expansion is a marketing job that most firms hand to sales, and then wonder where the revenue went.' },
    { name:'Happy to say so', vg:'adv',
      mindset:'This is now part of how I describe the portfolio.',
      question:'Will I put my name to this publicly?',
      thinks:'It works, and saying so makes the portfolio look forward-looking. That is free positioning for me.',
      does:'Gives a quote. Hosts a visit. Introduces a peer.',
      channels:['Case study','Joint PR','Conference stage','Peer introduction'],
      assets:['Named case study','Joint press release','Awards submission'],
      kpi:'Referenceable accounts, pipeline from referrals',
      owner:'ZAMSTARS Content',
      friction:'Ask at the right moment. Straight after a clean install works. During a renegotiation never does.' }
  ],

  lens:{
    'd-asset':{
      0:['Charging is a facilities line, not an asset decision.','Signs off the facilities budget without reading the detail.','Is this even on my P&amp;L?'],
      1:['Two renewals mentioned it. That is rent at risk.','Asks leasing how often it comes up on viewings.','How much rent is exposed to this?'],
      2:['I need to know which model does not need capital.','Reads the funding comparison.','Which option costs me nothing upfront?'],
      3:['Who has done this across a portfolio my size?','Asks the agent who covers the portfolio.','Who can standardise across twelve sites?'],
      4:['Prove it at the flagship first.','Grants access to one site.','What does this look like at my best asset?'],
      5:['No capital cost is the only reason this can happen.','Takes the revenue share model to finance.','What am I signing away, and does the site earn?'],
      6:['If occupiers notice, this becomes a leasing line.','Watches occupier feedback and renewals.','Did anyone notice?'],
      7:['Make it the portfolio standard and stop re-deciding.','Writes it into the specification.','How fast can we roll this out?'],
      8:['A charged portfolio is a positioning asset.','Speaks at a property forum about it.','Does saying this publicly help me?']
    },
    'd-sust':{
      0:['We have a target. Nobody has asked me how it gets met.','Writes the ESG report.','Will anyone fund any of this?'],
      1:['The report is due and the numbers are thin.','Pulls together what has actually been delivered.','What can I show that is real?'],
      2:['I need the option finance cannot say no to.','Compares funding models properly.','Which one removes the capital objection?'],
      3:['Who else in property has actually delivered this?','Asks peers in sustainability networks.','Who has done it, not just proposed it?'],
      4:['Engineering needs to be comfortable or this dies.','Brings engineering into the survey.','Will the grid take it?'],
      5:['This is where my projects usually die.','Builds the paper for finance and legal.','How do I get this approved?'],
      6:['Finally something delivered rather than pledged.','Puts it in the quarterly report.','Can I report this yet?'],
      7:['Now I have a template for every other site.','Proposes the rollout internally.','Can we standardise on this?'],
      8:['This is the case study my sector never has.','Presents it at a conference.','Will they let me talk about it?']
    }
  },

  kpiOverrides:{
    'Accounts with a named salesperson':[40,100],
    'Accounts where we know the committee':[15,90],
    'Accounts with three or more names':[5,75],
    'How complete the contact data is':[45,85],
    'Accounts that engaged':[4,12],
    'People engaged per account':[1.0,3.0],
    'Share who were senior':[25,55],
    'Visits from target accounts':[40,240],
    'Serious content actually read':[8,70],
    'Turned up to something':[0,24],
    'Came back within a month':[2,9],
    'Real conversations':[3,10],
    'Discovery meetings':[1,8],
    'Health checks delivered':[0,6],
    'Accounts sales has accepted':[2,9],
    'Opportunities created':[0,4],
    'Pipeline we created':[0,4],
    'Pipeline we helped':[0,7],
    'Average deal size':[120,180],
    'Win rate':[18,30],
    'How long deals took':[240,190],
    'Cost per engaged account':[0,150000],
    'Cost per real conversation':[0,180000],
    'Cost per opportunity':[0,450000]
  },

  playTweaks:{
    'Free connectivity health check':{ name:'Free site and grid assessment', desc:'We survey one of their car parks. Existing supply, spare capacity, where the ducting can run, how many bays are realistic in phase one, what the connection would cost if an upgrade is needed, and what to do first. They get a short report signed by an engineer. Everything else in this programme exists to earn this one meeting.' },
    'Send something they cannot ignore':{ name:'Post them their own car park', desc:'An aerial print of their own car park with the realistic phase one bays marked on it, couriered to the Head of Asset Management. Their site, their spaces, and not much to argue with.' },
    'Build the business case for them':{ name:'Model the revenue share and the renewals', desc:'We model revenue share, renewal retention and the capital avoided, using their own portfolio numbers. Written the way their finance team writes rather than the way we do.' },
    'Advertise inside their buildings':{ name:'Advertise around the business parks', desc:'Display served only around the parks and centres on the list, so every impression lands on somebody who parks there.' },
    'Standardise the portfolio':{ desc:'For groups running several sites. A maturity model, a workshop benchmarking their own car parks against each other, a standard technical approach, how reporting would work, and the cost and risk written up for their board. This is the play that turns one site into a portfolio agreement.' }
  },

  selectedPlays:['Free site and grid assessment','Move fast on a trigger','Lead with proof','Get in before the design is frozen','Standardise the portfolio','Put ten peers in a room','Do the homework','Write to them, on paper','Build them their own page','Take them to see it working','Model the revenue share and the renewals','Message the committee directly','Post them their own car park','Write the one document their sector needs','Pack the proof together','Put the guide in front of them','Let them price their own problem','Keep in touch properly','Stay visible to the whole list','Catch them while they are searching','Advertise around the business parks','Retarget by problem, not by page','Keep the slow ones warm','Let the field do the talking','Have a point of view in public','Make the proof findable'],

  method:'There are three parties in every Meridian deal. The landlord controls the space, the occupier or guest feels the absence, and the energy retailer rides on whatever gets installed. Almost all charging marketing talks to the driver, because the driver is the one complaining. We lead with the landlord instead. One agreement opens every site in a portfolio, and we use the occupiers asking at renewal as the argument that gets the landlord to move. What converts is not a brochure or a webinar. It is a grid assessment of a car park they already own, handed over as a short report. In a category nobody has budgeted for, the fastest way to create a budget line is to give someone evidence about their own asset.'
};

const BLANK = {
  id:'blank', name:'New client (blank)', short:'••', url:'',
  archetype:'infra', industry:'', hq:'', contact:'',
  exec:{ thesis:'', why:[], what:'', notThis:'', how:[], context:'' },
  successMetrics:[], metricsNote:'',
  profile:{ whatTheyDo:'', revenueModel:'', proof:[], diff:[], gtm:'', cycle:'', acv:'', competitors:'', challenge:'' },
  objective:{ goal:'', horizon:'90 day pilot', pipelineTarget:'', accountTarget:20, budget:0 },
  icpFit:[], disqualify:[],
  segments:[], personas:[], accounts:[], umbrellas:[], hooks:[], coreMessage:'', journey:null, method:''
};

const SHIPPED = [DEMO, BLANK];
